// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/route_matrix_element.proto

package com.google.maps.routes.v1;

public final class ComputeRouteMatrixElementProto {
  private ComputeRouteMatrixElementProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_maps_routes_v1_RouteMatrixElement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_maps_routes_v1_RouteMatrixElement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0google/maps/routes/v1/route_matrix_ele" +
      "ment.proto\022\025google.maps.routes.v1\032)googl" +
      "e/maps/routes/v1/fallback_info.proto\032!go" +
      "ogle/maps/routes/v1/route.proto\032\036google/" +
      "protobuf/duration.proto\032\027google/rpc/stat" +
      "us.proto\"\253\003\n\022RouteMatrixElement\022\024\n\014origi" +
      "n_index\030\001 \001(\005\022\031\n\021destination_index\030\002 \001(\005" +
      "\022\"\n\006status\030\003 \001(\0132\022.google.rpc.Status\022E\n\t" +
      "condition\030\t \001(\01622.google.maps.routes.v1." +
      "RouteMatrixElementCondition\022\027\n\017distance_" +
      "meters\030\004 \001(\005\022+\n\010duration\030\005 \001(\0132\031.google." +
      "protobuf.Duration\0222\n\017static_duration\030\006 \001" +
      "(\0132\031.google.protobuf.Duration\022C\n\017travel_" +
      "advisory\030\007 \001(\0132*.google.maps.routes.v1.R" +
      "outeTravelAdvisory\022:\n\rfallback_info\030\010 \001(" +
      "\0132#.google.maps.routes.v1.FallbackInfo*t" +
      "\n\033RouteMatrixElementCondition\022.\n*ROUTE_M" +
      "ATRIX_ELEMENT_CONDITION_UNSPECIFIED\020\000\022\020\n" +
      "\014ROUTE_EXISTS\020\001\022\023\n\017ROUTE_NOT_FOUND\020\002B\264\001\n" +
      "\031com.google.maps.routes.v1B\036ComputeRoute" +
      "MatrixElementProtoP\001Z;google.golang.org/" +
      "genproto/googleapis/maps/routes/v1;route" +
      "s\370\001\001\242\002\004GMRS\252\002\025Google.Maps.Routes.V1\312\002\025Go" +
      "ogle\\Maps\\Routes\\V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.maps.routes.v1.FallbackInfoProto.getDescriptor(),
          com.google.maps.routes.v1.RouteProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
        });
    internal_static_google_maps_routes_v1_RouteMatrixElement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_maps_routes_v1_RouteMatrixElement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_maps_routes_v1_RouteMatrixElement_descriptor,
        new java.lang.String[] { "OriginIndex", "DestinationIndex", "Status", "Condition", "DistanceMeters", "Duration", "StaticDuration", "TravelAdvisory", "FallbackInfo", });
    com.google.maps.routes.v1.FallbackInfoProto.getDescriptor();
    com.google.maps.routes.v1.RouteProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
