// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/route.proto

package com.google.maps.routes.v1;

public interface RouteLegStepTravelAdvisoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.maps.routes.v1.RouteLegStepTravelAdvisory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Speed reading intervals detailing traffic density. Applicable in case of
   * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
   * The intervals cover the entire polyline of the RouteLegStep without
   * overlaps, i.e. the start point of a given interval coincides with the end
   * point of the preceding interval.
   * Example:
   *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
   *     speed_reading_intervals: [A,C), [C,D), [D,G).
   * </pre>
   *
   * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
   */
  java.util.List<com.google.maps.routes.v1.SpeedReadingInterval> 
      getSpeedReadingIntervalsList();
  /**
   * <pre>
   * Speed reading intervals detailing traffic density. Applicable in case of
   * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
   * The intervals cover the entire polyline of the RouteLegStep without
   * overlaps, i.e. the start point of a given interval coincides with the end
   * point of the preceding interval.
   * Example:
   *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
   *     speed_reading_intervals: [A,C), [C,D), [D,G).
   * </pre>
   *
   * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
   */
  com.google.maps.routes.v1.SpeedReadingInterval getSpeedReadingIntervals(int index);
  /**
   * <pre>
   * Speed reading intervals detailing traffic density. Applicable in case of
   * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
   * The intervals cover the entire polyline of the RouteLegStep without
   * overlaps, i.e. the start point of a given interval coincides with the end
   * point of the preceding interval.
   * Example:
   *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
   *     speed_reading_intervals: [A,C), [C,D), [D,G).
   * </pre>
   *
   * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
   */
  int getSpeedReadingIntervalsCount();
  /**
   * <pre>
   * Speed reading intervals detailing traffic density. Applicable in case of
   * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
   * The intervals cover the entire polyline of the RouteLegStep without
   * overlaps, i.e. the start point of a given interval coincides with the end
   * point of the preceding interval.
   * Example:
   *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
   *     speed_reading_intervals: [A,C), [C,D), [D,G).
   * </pre>
   *
   * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
   */
  java.util.List<? extends com.google.maps.routes.v1.SpeedReadingIntervalOrBuilder> 
      getSpeedReadingIntervalsOrBuilderList();
  /**
   * <pre>
   * Speed reading intervals detailing traffic density. Applicable in case of
   * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
   * The intervals cover the entire polyline of the RouteLegStep without
   * overlaps, i.e. the start point of a given interval coincides with the end
   * point of the preceding interval.
   * Example:
   *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
   *     speed_reading_intervals: [A,C), [C,D), [D,G).
   * </pre>
   *
   * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
   */
  com.google.maps.routes.v1.SpeedReadingIntervalOrBuilder getSpeedReadingIntervalsOrBuilder(
      int index);
}
