// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/route.proto

package com.google.maps.routes.v1;

/**
 * <pre>
 * Encapsulates the additional information that the user should be informed
 * about, such as possible traffic zone restriction etc. on a leg step.
 * </pre>
 *
 * Protobuf type {@code google.maps.routes.v1.RouteLegStepTravelAdvisory}
 */
public final class RouteLegStepTravelAdvisory extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.maps.routes.v1.RouteLegStepTravelAdvisory)
    RouteLegStepTravelAdvisoryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RouteLegStepTravelAdvisory.newBuilder() to construct.
  private RouteLegStepTravelAdvisory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RouteLegStepTravelAdvisory() {
    speedReadingIntervals_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RouteLegStepTravelAdvisory();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RouteLegStepTravelAdvisory(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              speedReadingIntervals_ = new java.util.ArrayList<com.google.maps.routes.v1.SpeedReadingInterval>();
              mutable_bitField0_ |= 0x00000001;
            }
            speedReadingIntervals_.add(
                input.readMessage(com.google.maps.routes.v1.SpeedReadingInterval.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        speedReadingIntervals_ = java.util.Collections.unmodifiableList(speedReadingIntervals_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_RouteLegStepTravelAdvisory_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_RouteLegStepTravelAdvisory_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.maps.routes.v1.RouteLegStepTravelAdvisory.class, com.google.maps.routes.v1.RouteLegStepTravelAdvisory.Builder.class);
  }

  public static final int SPEED_READING_INTERVALS_FIELD_NUMBER = 1;
  private java.util.List<com.google.maps.routes.v1.SpeedReadingInterval> speedReadingIntervals_;
  /**
   * <pre>
   * Speed reading intervals detailing traffic density. Applicable in case of
   * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
   * The intervals cover the entire polyline of the RouteLegStep without
   * overlaps, i.e. the start point of a given interval coincides with the end
   * point of the preceding interval.
   * Example:
   *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
   *     speed_reading_intervals: [A,C), [C,D), [D,G).
   * </pre>
   *
   * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.maps.routes.v1.SpeedReadingInterval> getSpeedReadingIntervalsList() {
    return speedReadingIntervals_;
  }
  /**
   * <pre>
   * Speed reading intervals detailing traffic density. Applicable in case of
   * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
   * The intervals cover the entire polyline of the RouteLegStep without
   * overlaps, i.e. the start point of a given interval coincides with the end
   * point of the preceding interval.
   * Example:
   *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
   *     speed_reading_intervals: [A,C), [C,D), [D,G).
   * </pre>
   *
   * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.maps.routes.v1.SpeedReadingIntervalOrBuilder> 
      getSpeedReadingIntervalsOrBuilderList() {
    return speedReadingIntervals_;
  }
  /**
   * <pre>
   * Speed reading intervals detailing traffic density. Applicable in case of
   * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
   * The intervals cover the entire polyline of the RouteLegStep without
   * overlaps, i.e. the start point of a given interval coincides with the end
   * point of the preceding interval.
   * Example:
   *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
   *     speed_reading_intervals: [A,C), [C,D), [D,G).
   * </pre>
   *
   * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
   */
  @java.lang.Override
  public int getSpeedReadingIntervalsCount() {
    return speedReadingIntervals_.size();
  }
  /**
   * <pre>
   * Speed reading intervals detailing traffic density. Applicable in case of
   * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
   * The intervals cover the entire polyline of the RouteLegStep without
   * overlaps, i.e. the start point of a given interval coincides with the end
   * point of the preceding interval.
   * Example:
   *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
   *     speed_reading_intervals: [A,C), [C,D), [D,G).
   * </pre>
   *
   * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
   */
  @java.lang.Override
  public com.google.maps.routes.v1.SpeedReadingInterval getSpeedReadingIntervals(int index) {
    return speedReadingIntervals_.get(index);
  }
  /**
   * <pre>
   * Speed reading intervals detailing traffic density. Applicable in case of
   * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
   * The intervals cover the entire polyline of the RouteLegStep without
   * overlaps, i.e. the start point of a given interval coincides with the end
   * point of the preceding interval.
   * Example:
   *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
   *     speed_reading_intervals: [A,C), [C,D), [D,G).
   * </pre>
   *
   * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
   */
  @java.lang.Override
  public com.google.maps.routes.v1.SpeedReadingIntervalOrBuilder getSpeedReadingIntervalsOrBuilder(
      int index) {
    return speedReadingIntervals_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < speedReadingIntervals_.size(); i++) {
      output.writeMessage(1, speedReadingIntervals_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < speedReadingIntervals_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, speedReadingIntervals_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.maps.routes.v1.RouteLegStepTravelAdvisory)) {
      return super.equals(obj);
    }
    com.google.maps.routes.v1.RouteLegStepTravelAdvisory other = (com.google.maps.routes.v1.RouteLegStepTravelAdvisory) obj;

    if (!getSpeedReadingIntervalsList()
        .equals(other.getSpeedReadingIntervalsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSpeedReadingIntervalsCount() > 0) {
      hash = (37 * hash) + SPEED_READING_INTERVALS_FIELD_NUMBER;
      hash = (53 * hash) + getSpeedReadingIntervalsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.maps.routes.v1.RouteLegStepTravelAdvisory parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.RouteLegStepTravelAdvisory parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.RouteLegStepTravelAdvisory parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.RouteLegStepTravelAdvisory parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.RouteLegStepTravelAdvisory parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.RouteLegStepTravelAdvisory parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.RouteLegStepTravelAdvisory parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.RouteLegStepTravelAdvisory parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.maps.routes.v1.RouteLegStepTravelAdvisory parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.RouteLegStepTravelAdvisory parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.maps.routes.v1.RouteLegStepTravelAdvisory parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.RouteLegStepTravelAdvisory parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.maps.routes.v1.RouteLegStepTravelAdvisory prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Encapsulates the additional information that the user should be informed
   * about, such as possible traffic zone restriction etc. on a leg step.
   * </pre>
   *
   * Protobuf type {@code google.maps.routes.v1.RouteLegStepTravelAdvisory}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.maps.routes.v1.RouteLegStepTravelAdvisory)
      com.google.maps.routes.v1.RouteLegStepTravelAdvisoryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_RouteLegStepTravelAdvisory_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_RouteLegStepTravelAdvisory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.maps.routes.v1.RouteLegStepTravelAdvisory.class, com.google.maps.routes.v1.RouteLegStepTravelAdvisory.Builder.class);
    }

    // Construct using com.google.maps.routes.v1.RouteLegStepTravelAdvisory.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSpeedReadingIntervalsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (speedReadingIntervalsBuilder_ == null) {
        speedReadingIntervals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        speedReadingIntervalsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_RouteLegStepTravelAdvisory_descriptor;
    }

    @java.lang.Override
    public com.google.maps.routes.v1.RouteLegStepTravelAdvisory getDefaultInstanceForType() {
      return com.google.maps.routes.v1.RouteLegStepTravelAdvisory.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.maps.routes.v1.RouteLegStepTravelAdvisory build() {
      com.google.maps.routes.v1.RouteLegStepTravelAdvisory result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.maps.routes.v1.RouteLegStepTravelAdvisory buildPartial() {
      com.google.maps.routes.v1.RouteLegStepTravelAdvisory result = new com.google.maps.routes.v1.RouteLegStepTravelAdvisory(this);
      int from_bitField0_ = bitField0_;
      if (speedReadingIntervalsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          speedReadingIntervals_ = java.util.Collections.unmodifiableList(speedReadingIntervals_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.speedReadingIntervals_ = speedReadingIntervals_;
      } else {
        result.speedReadingIntervals_ = speedReadingIntervalsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.maps.routes.v1.RouteLegStepTravelAdvisory) {
        return mergeFrom((com.google.maps.routes.v1.RouteLegStepTravelAdvisory)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.maps.routes.v1.RouteLegStepTravelAdvisory other) {
      if (other == com.google.maps.routes.v1.RouteLegStepTravelAdvisory.getDefaultInstance()) return this;
      if (speedReadingIntervalsBuilder_ == null) {
        if (!other.speedReadingIntervals_.isEmpty()) {
          if (speedReadingIntervals_.isEmpty()) {
            speedReadingIntervals_ = other.speedReadingIntervals_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSpeedReadingIntervalsIsMutable();
            speedReadingIntervals_.addAll(other.speedReadingIntervals_);
          }
          onChanged();
        }
      } else {
        if (!other.speedReadingIntervals_.isEmpty()) {
          if (speedReadingIntervalsBuilder_.isEmpty()) {
            speedReadingIntervalsBuilder_.dispose();
            speedReadingIntervalsBuilder_ = null;
            speedReadingIntervals_ = other.speedReadingIntervals_;
            bitField0_ = (bitField0_ & ~0x00000001);
            speedReadingIntervalsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSpeedReadingIntervalsFieldBuilder() : null;
          } else {
            speedReadingIntervalsBuilder_.addAllMessages(other.speedReadingIntervals_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.maps.routes.v1.RouteLegStepTravelAdvisory parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.maps.routes.v1.RouteLegStepTravelAdvisory) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.maps.routes.v1.SpeedReadingInterval> speedReadingIntervals_ =
      java.util.Collections.emptyList();
    private void ensureSpeedReadingIntervalsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        speedReadingIntervals_ = new java.util.ArrayList<com.google.maps.routes.v1.SpeedReadingInterval>(speedReadingIntervals_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.maps.routes.v1.SpeedReadingInterval, com.google.maps.routes.v1.SpeedReadingInterval.Builder, com.google.maps.routes.v1.SpeedReadingIntervalOrBuilder> speedReadingIntervalsBuilder_;

    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public java.util.List<com.google.maps.routes.v1.SpeedReadingInterval> getSpeedReadingIntervalsList() {
      if (speedReadingIntervalsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(speedReadingIntervals_);
      } else {
        return speedReadingIntervalsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public int getSpeedReadingIntervalsCount() {
      if (speedReadingIntervalsBuilder_ == null) {
        return speedReadingIntervals_.size();
      } else {
        return speedReadingIntervalsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public com.google.maps.routes.v1.SpeedReadingInterval getSpeedReadingIntervals(int index) {
      if (speedReadingIntervalsBuilder_ == null) {
        return speedReadingIntervals_.get(index);
      } else {
        return speedReadingIntervalsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public Builder setSpeedReadingIntervals(
        int index, com.google.maps.routes.v1.SpeedReadingInterval value) {
      if (speedReadingIntervalsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpeedReadingIntervalsIsMutable();
        speedReadingIntervals_.set(index, value);
        onChanged();
      } else {
        speedReadingIntervalsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public Builder setSpeedReadingIntervals(
        int index, com.google.maps.routes.v1.SpeedReadingInterval.Builder builderForValue) {
      if (speedReadingIntervalsBuilder_ == null) {
        ensureSpeedReadingIntervalsIsMutable();
        speedReadingIntervals_.set(index, builderForValue.build());
        onChanged();
      } else {
        speedReadingIntervalsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public Builder addSpeedReadingIntervals(com.google.maps.routes.v1.SpeedReadingInterval value) {
      if (speedReadingIntervalsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpeedReadingIntervalsIsMutable();
        speedReadingIntervals_.add(value);
        onChanged();
      } else {
        speedReadingIntervalsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public Builder addSpeedReadingIntervals(
        int index, com.google.maps.routes.v1.SpeedReadingInterval value) {
      if (speedReadingIntervalsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpeedReadingIntervalsIsMutable();
        speedReadingIntervals_.add(index, value);
        onChanged();
      } else {
        speedReadingIntervalsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public Builder addSpeedReadingIntervals(
        com.google.maps.routes.v1.SpeedReadingInterval.Builder builderForValue) {
      if (speedReadingIntervalsBuilder_ == null) {
        ensureSpeedReadingIntervalsIsMutable();
        speedReadingIntervals_.add(builderForValue.build());
        onChanged();
      } else {
        speedReadingIntervalsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public Builder addSpeedReadingIntervals(
        int index, com.google.maps.routes.v1.SpeedReadingInterval.Builder builderForValue) {
      if (speedReadingIntervalsBuilder_ == null) {
        ensureSpeedReadingIntervalsIsMutable();
        speedReadingIntervals_.add(index, builderForValue.build());
        onChanged();
      } else {
        speedReadingIntervalsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public Builder addAllSpeedReadingIntervals(
        java.lang.Iterable<? extends com.google.maps.routes.v1.SpeedReadingInterval> values) {
      if (speedReadingIntervalsBuilder_ == null) {
        ensureSpeedReadingIntervalsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, speedReadingIntervals_);
        onChanged();
      } else {
        speedReadingIntervalsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public Builder clearSpeedReadingIntervals() {
      if (speedReadingIntervalsBuilder_ == null) {
        speedReadingIntervals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        speedReadingIntervalsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public Builder removeSpeedReadingIntervals(int index) {
      if (speedReadingIntervalsBuilder_ == null) {
        ensureSpeedReadingIntervalsIsMutable();
        speedReadingIntervals_.remove(index);
        onChanged();
      } else {
        speedReadingIntervalsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public com.google.maps.routes.v1.SpeedReadingInterval.Builder getSpeedReadingIntervalsBuilder(
        int index) {
      return getSpeedReadingIntervalsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public com.google.maps.routes.v1.SpeedReadingIntervalOrBuilder getSpeedReadingIntervalsOrBuilder(
        int index) {
      if (speedReadingIntervalsBuilder_ == null) {
        return speedReadingIntervals_.get(index);  } else {
        return speedReadingIntervalsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public java.util.List<? extends com.google.maps.routes.v1.SpeedReadingIntervalOrBuilder> 
         getSpeedReadingIntervalsOrBuilderList() {
      if (speedReadingIntervalsBuilder_ != null) {
        return speedReadingIntervalsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(speedReadingIntervals_);
      }
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public com.google.maps.routes.v1.SpeedReadingInterval.Builder addSpeedReadingIntervalsBuilder() {
      return getSpeedReadingIntervalsFieldBuilder().addBuilder(
          com.google.maps.routes.v1.SpeedReadingInterval.getDefaultInstance());
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public com.google.maps.routes.v1.SpeedReadingInterval.Builder addSpeedReadingIntervalsBuilder(
        int index) {
      return getSpeedReadingIntervalsFieldBuilder().addBuilder(
          index, com.google.maps.routes.v1.SpeedReadingInterval.getDefaultInstance());
    }
    /**
     * <pre>
     * Speed reading intervals detailing traffic density. Applicable in case of
     * `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
     * The intervals cover the entire polyline of the RouteLegStep without
     * overlaps, i.e. the start point of a given interval coincides with the end
     * point of the preceding interval.
     * Example:
     *     polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
     *     speed_reading_intervals: [A,C), [C,D), [D,G).
     * </pre>
     *
     * <code>repeated .google.maps.routes.v1.SpeedReadingInterval speed_reading_intervals = 1;</code>
     */
    public java.util.List<com.google.maps.routes.v1.SpeedReadingInterval.Builder> 
         getSpeedReadingIntervalsBuilderList() {
      return getSpeedReadingIntervalsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.maps.routes.v1.SpeedReadingInterval, com.google.maps.routes.v1.SpeedReadingInterval.Builder, com.google.maps.routes.v1.SpeedReadingIntervalOrBuilder> 
        getSpeedReadingIntervalsFieldBuilder() {
      if (speedReadingIntervalsBuilder_ == null) {
        speedReadingIntervalsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.maps.routes.v1.SpeedReadingInterval, com.google.maps.routes.v1.SpeedReadingInterval.Builder, com.google.maps.routes.v1.SpeedReadingIntervalOrBuilder>(
                speedReadingIntervals_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        speedReadingIntervals_ = null;
      }
      return speedReadingIntervalsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.maps.routes.v1.RouteLegStepTravelAdvisory)
  }

  // @@protoc_insertion_point(class_scope:google.maps.routes.v1.RouteLegStepTravelAdvisory)
  private static final com.google.maps.routes.v1.RouteLegStepTravelAdvisory DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.maps.routes.v1.RouteLegStepTravelAdvisory();
  }

  public static com.google.maps.routes.v1.RouteLegStepTravelAdvisory getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RouteLegStepTravelAdvisory>
      PARSER = new com.google.protobuf.AbstractParser<RouteLegStepTravelAdvisory>() {
    @java.lang.Override
    public RouteLegStepTravelAdvisory parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RouteLegStepTravelAdvisory(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RouteLegStepTravelAdvisory> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RouteLegStepTravelAdvisory> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.maps.routes.v1.RouteLegStepTravelAdvisory getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

