// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/route.proto

package com.google.maps.routes.v1;

public interface SpeedReadingIntervalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.maps.routes.v1.SpeedReadingInterval)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The starting index of this interval in the polyline.
   * In JSON, when the index is 0, the field will appear to be unpopulated.
   * </pre>
   *
   * <code>int32 start_polyline_point_index = 1;</code>
   * @return The startPolylinePointIndex.
   */
  int getStartPolylinePointIndex();

  /**
   * <pre>
   * The ending index of this interval in the polyline.
   * In JSON, when the index is 0, the field will appear to be unpopulated.
   * </pre>
   *
   * <code>int32 end_polyline_point_index = 2;</code>
   * @return The endPolylinePointIndex.
   */
  int getEndPolylinePointIndex();

  /**
   * <pre>
   * Traffic speed in this interval.
   * </pre>
   *
   * <code>.google.maps.routes.v1.SpeedReadingInterval.Speed speed = 3;</code>
   * @return The enum numeric value on the wire for speed.
   */
  int getSpeedValue();
  /**
   * <pre>
   * Traffic speed in this interval.
   * </pre>
   *
   * <code>.google.maps.routes.v1.SpeedReadingInterval.Speed speed = 3;</code>
   * @return The speed.
   */
  com.google.maps.routes.v1.SpeedReadingInterval.Speed getSpeed();
}
